[package]
name = "holg"
version = "1.0.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"
chrono = "0.4"

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = true
incremental = false
codegen-units = 16
rpath = false

