name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history including tags
          ref: ${{ github.ref }} # checkout the tag commit
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: sudo apt-get update && sudo apt-get install -y musl-tools musl-dev
      - run: rustup update
      - run: cargo install --locked cargo-zigbuild
      - run: python3 ci/build.py
      - uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: build/*

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - run: rustup update
      - run: python3 ci/build.py
      - uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: build/*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - run: rustup update
      - run: python ci/build.py
      - uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: build/*

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Prepare build dir
        run: |
          mkdir -p build
          cp -r artifacts/*/* build/
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          set -e
          FILES=$(find build -type f)
          if [ -z "$FILES" ]; then
            echo "[!] No archives found to upload."
            exit 0
          fi

          gh release create "$TAG" \
            --repo "$GITHUB_REPOSITORY" \
            --title "HOLG ${TAG#v}" \
            --generate-notes \
            $FILES
